name: CI

on:
  push:
    branches:
      - master

jobs:

  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 12.16
      - name: yarn
        run: npm install -g yarn
      - name: install
        run: yarn install
      - name: build
        run: yarn run pack:mac
      - name: see-directory
        run: ls

  win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 12.16
      - name: install
        run: npm install -g yarn
      - name: install
        run: yarn install
      - name: build
        run: yarn run pack:win
      - name: see-directory
        run: ls
